// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lange_Final_API.Models
{
    public partial class Driver
    {
        public string DriverLicenseNumber { get; set; }
        public string DriverFirstName { get; set; }
        public string DriverLastName { get; set; }
        public string DriverSocialSecurity { get; set; }
        public string DriverPhoneNumber { get; set; }
    }
}