// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lange_Final_API.Models
{
    public partial class DriversInfraction
    {
        public string DriverLicenseNumber { get; set; }
        public string InfractionId { get; set; }
    }
}