// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lange_Final_API.Models
{
    public partial class Infraction
    {
        public string InfractionId { get; set; }
        public string InfractionName { get; set; }
        public string InfractionFine { get; set; }
        public DateTime? InfractionDate { get; set; }
    }
}